UniEnrollment/UniEnrollment-MVC/Models/Course.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniEnrollment_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Enrollments = new HashSet<Enrollment>();
        }
    
        public int ID { get; set; }
        public int ProfessorID { get; set; }
        public string CourseCode { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrollment> Enrollments { get; set; }
    }
}

UniEnrollment/UniEnrollment-MVC/Models/CourseViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web.Mvc;

namespace UniEnrollment_MVC.Models
{
    public class CourseViewModel
    {
        public int ID { get; set; }

        [Display(Name = "Professor")]
        [Required]
        public int ProfessorID { get; set; }

        [Display(Name = "Course Code")]
        [StringLength(20, ErrorMessage = "Course code cannot be more than 20 characters long")]
        [Required]
        public string CourseCode { get; set; }

        [Display(Name = "Course Name")]
        [StringLength(100, ErrorMessage = "Course name / title cannot be more than 100 characters long")]
        [Required]
        public string Name { get; set; }
        
        [Display(Name = "Course Description")]
        [Required]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        /// <summary>
        /// Returns the user 'Name' from their ID. Not strinctly required for most related views, the business models
        /// (seen in the DataMode.edmx) are related so you can just call from e.g. Model.Course.Professor.Name
        /// however I used this out of scope once so it's useful
        /// </summary>
        /// <param name="id">ID of user</param>
        /// <returns>Name of the professor (or user)</returns>
        public static string GetProfessorNameByID(int id)
        {
            return new UniEnrollmentDBEntities().Users.Where(p => p.ID == id).FirstOrDefault().Name;
        }

        /// <summary>
        /// Returns a list of courses specifically for use in drop down lsits
        /// </summary>
        /// <returns>List of courses</returns>
        public static List<Course> GetCourseList()
        {
            return new UniEnrollmentDBEntities().Courses.ToList();
        }

        /// <summary>
        /// Get a list of courses ran by a specific professor
        /// </summary>
        /// <param name="id">ID of professor (or user)</param>
        /// <returns>List of courses ran by specific professor</returns>
        public static List<Course> GetCourseListByProfessorID(int id)
        {
            return new UniEnrollmentDBEntities().Courses.Where(c => c.ProfessorID == id).ToList();
        }
    }
}

UniEnrollment/UniEnrollment-MVC/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniEnrollment_MVC.Helpers;
using UniEnrollment_MVC.Models;

namespace UniEnrollment_MVC.Controllers
{
    /// <summary>
    /// Contains user interaction (action result) methods for anything uni 'course' related
    /// </summary>
    public class CourseController : Controller
    {
        private UniEnrollmentDBEntities _entities = new UniEnrollmentDBEntities();

        public ActionResult Index()
        {
            return View(_entities.Courses.ToList());
        }

        [HttpGet]
        public ActionResult Create()
        {
            // tiny security check...
            if (CookieHelper.LoggedInUserType == CookieHelper.LoggedInUserTypeEnum.STUDENT || !CookieHelper.IsLoggedIn())
            {
                return View("Index", _entities.Courses.ToList());
            }

            ModelState.Clear();
            return View(new CourseViewModel());
        }

        [HttpGet]
        public ActionResult CreateWithID(int? id)
        {
            // tiny security check...
            if (CookieHelper.LoggedInUserType == CookieHelper.LoggedInUserTypeEnum.STUDENT || !CookieHelper.IsLoggedIn())
            {
                return View("Index", _entities.Courses.ToList());
            }

            ModelState.Clear();
            ViewBag.Professor = _entities.Users.Single(p => p.ID == (int)id);

            return View(new CourseViewModel());
        }

        [HttpPost]
        public ActionResult SubmitCreate(CourseViewModel vmCourse)
        {
            if (ModelState.IsValid)
            {

                if (_entities.Courses.Any(s => s.Name == vmCourse.Name))
                {
                    ModelState.AddModelError(String.Empty, "That course code already exists");
                    ModelState.AddModelError("CourseCodeError", "That course code already exists");

                    return View("Create", new CourseViewModel());
                }
                else
                {
                    Course newCourse = new Course
                    {
                        CourseCode = vmCourse.CourseCode,
                        Name = vmCourse.Name,
                        Description = vmCourse.Description,
                        ProfessorID = vmCourse.ProfessorID
                    };

                    _entities.Courses.Add(newCourse);
                    _entities.Entry(newCourse).State = EntityState.Added;
                    _entities.SaveChanges();

                    return View("Index", _entities.Courses.ToList());
                }
            }
            else
            {
                return View("Create", new CourseViewModel());
            }
        }

        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id != null)
            {
                if (_entities.Courses.Any(s => s.ID == id))
                {
                    return View(_entities.Courses.Single(c => c.ID == id));
                }
            }

            return View("Index", _entities.Courses.ToList());
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            // tiny security check...
            if (CookieHelper.LoggedInUserType == CookieHelper.LoggedInUserTypeEnum.STUDENT || !CookieHelper.IsLoggedIn())
            {
                return View("Index", _entities.Courses.ToList());
            }

            ModelState.Clear();

            if (id != null)
            {
                // bit of validation...
                if (_entities.Courses.Any(s => s.ID == id))
                {
                    return View(_entities.Courses.Single(c => c.ID == id));
                }
            }

            return View("Index", _entities.Courses.ToList());
        }

        [HttpPost]
        public ActionResult SubmitEdit(Course course)
        {
            if (ModelState.IsValid)
            {
                _entities.Entry(course).State = EntityState.Modified;
                _entities.SaveChanges();

                return View("Index", _entities.Courses.ToList());
            }
            else
            {
                return View("Edit", _entities.Courses.Single(c => c.ID == course.ID));
            }
        }

        public ActionResult Delete(int? id)
        {
            // tiny security check...
            if (CookieHelper.LoggedInUserType == CookieHelper.LoggedInUserTypeEnum.STUDENT || !CookieHelper.IsLoggedIn())
            {
                return View("Index", _entities.Courses.ToList());
            }

            if (id != null)
            {
                // bit of validation...
                if (_entities.Courses.Any(s => s.ID == id))
                {
                    var course = _entities.Courses.Single(c => c.ID == id);
                    _entities.Courses.Remove(course);
                    _entities.Entry(course).State = EntityState.Deleted;
                    _entities.SaveChanges();

                    return View("Index", _entities.Courses.ToList());
                }
            }

            return View("Index", _entities.Courses.ToList());
        }
    }
}

UniEnrollment/UniEnrollment-MVC/Controllers/EnrollmentController.cs
using System.Linq;
using System.Web.Mvc;
using UniEnrollment_MVC.Helpers;
using UniEnrollment_MVC.Models;

namespace UniEnrollment_MVC.Controllers
{
    /// <summary>
    /// Contains user interaction (action result) methods for anything uni 'enrollment' related
    /// </summary>
    public class EnrollmentController : Controller
    {
        private UniEnrollmentDBEntities _entities = new UniEnrollmentDBEntities();

        public ActionResult Index()
        {
            // tiny security check...
            if (CookieHelper.LoggedInUserType == CookieHelper.LoggedInUserTypeEnum.STUDENT || !CookieHelper.IsLoggedIn())
            {
                return RedirectToAction("Index", "Home", null);
            }

            return View(_entities.Enrollments.ToList());
        }
    }
}

UniEnrollment/UniEnrollment-MVC/Views/Course/Create.cshtml
@model UniEnrollment_MVC.Models.CourseViewModel

@{
    ViewBag.Title = "Create Course";
}

<h2>Create Course</h2>


@using (Html.BeginForm("SubmitCreate", "Course", FormMethod.Post, new { @encType = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProfessorID, "Professor", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.ProfessorID, new
                    SelectList(UniEnrollment_MVC.Models.ProfessorViewModel.GetProfessorList().AsEnumerable(), "ID", "Name"), new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseCode, "", new { @class = "text-danger" })
                @Html.ValidationMessage("CourseCodeError", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Courses List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UniEnrollment/UniEnrollment-MVC/Views/Course/CreateWithID.cshtml
@model UniEnrollment_MVC.Models.CourseViewModel

@{
    ViewBag.Title = "Create Course";

    UniEnrollment_MVC.Models.User prof = (UniEnrollment_MVC.Models.User)ViewBag.Professor;
    Model.ProfessorID = prof.ID;
}

<h2>Create Course</h2>


@using (Html.BeginForm("SubmitCreate", "Course", FormMethod.Post, new { @encType = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, "Professor Name", htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.HiddenFor(model => model.ProfessorID)
            <div class="col-md-10">
                <p style="margin-top: 7px;">@prof.Name</p>                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseCode, "", new { @class = "text-danger" })
                @Html.ValidationMessage("CourseCodeError", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UniEnrollment/UniEnrollment-MVC/Views/Course/Details.cshtml
@model UniEnrollment_MVC.Models.Course

@{
    ViewBag.Title = "Details";
}

<h2>Course Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
            <br /><br />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CourseCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourseCode)
            <br /><br />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
            <br /><br />
        </dd>

        <dt>
            Course Run By
        </dt>

        <dd>
            @Html.ActionLink(UniEnrollment_MVC.Models.CourseViewModel.GetProfessorNameByID(Model.ProfessorID),
                "Details", "Professor", new { id = Model.ProfessorID }, null)<br />

            <br /><br />
        </dd>

    </dl>


</div>
<p>
    @if (!(UniEnrollment_MVC.Helpers.CookieHelper.LoggedInUserType == UniEnrollment_MVC.Helpers.CookieHelper.LoggedInUserTypeEnum.STUDENT) 
        && UniEnrollment_MVC.Helpers.CookieHelper.IsLoggedIn())
    {
        <span>@Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |</span>
    }
    @Html.ActionLink("Courses List", "Index")
</p>
<br />

<br />

@if (!(UniEnrollment_MVC.Helpers.CookieHelper.LoggedInUserType == UniEnrollment_MVC.Helpers.CookieHelper.LoggedInUserTypeEnum.STUDENT) 
    && UniEnrollment_MVC.Helpers.CookieHelper.IsLoggedIn())
{
    <span style="font-weight: bold;">Current Students Enrolled on This Course</span><br /><br />

    foreach (var item in UniEnrollment_MVC.Models.EnrollmentViewModel.GetStudentsEnrolledOnCourse(Model.ID))
    {
        @Html.ActionLink(item.Name, "Details", "Student", new { id = Model.ID }, null)<br />
    }
}

UniEnrollment/UniEnrollment-MVC/Views/Course/Edit.cshtml
@model UniEnrollment_MVC.Models.Course

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Course</h2>


@using (Html.BeginForm("SubmitEdit", "Course", FormMethod.Post, new { @encType = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.ProfessorID, "ProfessorID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.ProfessorID, new SelectList(UniEnrollment_MVC.Models.ProfessorViewModel.GetProfessorList().AsEnumerable(), "ID", "Name"),
                       new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10 editor-multiline-field">
                @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Courses List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UniEnrollment/UniEnrollment-MVC/Views/Course/Index.cshtml
@model IEnumerable<UniEnrollment_MVC.Models.Course>

@{
    ViewBag.Title = "Courses";
}

<h2>Courses</h2>
<br />
<p>
    @if (!(UniEnrollment_MVC.Helpers.CookieHelper.LoggedInUserType == UniEnrollment_MVC.Helpers.CookieHelper.LoggedInUserTypeEnum.STUDENT)
                            && UniEnrollment_MVC.Helpers.CookieHelper.IsLoggedIn())
    {
        @Html.ActionLink("Create New", "Create")
    }
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CourseCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            Ran By Professor
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(@item.Name, "Details", new { id = item.ID })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CourseCode)
            </td>
            <td style="width: 40%;">
                @item.Description.Substring(0, Math.Min(item.Description.Length, 200))
                @Html.ActionLink("...", "Details", new { id = item.ID }, new { @style = "font-weight: bold;" })
            </td>
            <td>
                @Html.ActionLink(@UniEnrollment_MVC.Models.CourseViewModel.GetProfessorNameByID(item.ProfessorID),
                    "Details", "Professor", new { id = item.ProfessorID }, null)

            </td>
            <td>
                @if (!(UniEnrollment_MVC.Helpers.CookieHelper.LoggedInUserType == UniEnrollment_MVC.Helpers.CookieHelper.LoggedInUserTypeEnum.STUDENT)
                    && UniEnrollment_MVC.Helpers.CookieHelper.IsLoggedIn())
                {
                    <span>@Html.ActionLink("Edit", "Edit", new { id = item.ID }) |</span>

                    <span>
                        @Html.ActionLink(
                    "Delete",
                    "Delete",
                    "Course",
                    new { id = item.ID }, new { onclick = "return confirm('Do you really want to delete this course?')" }) |
                    </span>
                }

                @Html.ActionLink("Details", "Details", new { id = item.ID })
            </td>
        </tr>
    }
</table>
<br />
<br />
<p>
    @if (!(UniEnrollment_MVC.Helpers.CookieHelper.LoggedInUserType == UniEnrollment_MVC.Helpers.CookieHelper.LoggedInUserTypeEnum.STUDENT) &&
                UniEnrollment_MVC.Helpers.CookieHelper.IsLoggedIn())
    {
        <span>@Html.ActionLink("Courses Enrollment List", "Index", "Enrollment", null, null)</span>
    }
</p>